export default [
  {
    id: 90001,
    name: 'Acme Inc.',
    domain: 'acme.com',
    contactsCount: 12,
    additionalAttributes: {
      industry: 'Software',
      phone: '+1 (555) 123-4567',
      email: 'hello@acme.com',
      website: 'www.acme.com',
      owner: 'Jane Doe',
    },
  },
  {
    id: 90002,
    name: 'Global Tech',
    domain: 'apple.com',
    contactsCount: 8,
    additionalAttributes: {
      industry: 'Manufacturing',
      phone: '+1 (555) 987-6543',
      email: 'contact@apple.com',
      website: 'www.apple.com',
      owner: 'John Smith',
    },
  },
  {
    id: 90003,
    name: 'Stark Industries',
    domain: 'tesla.com',
    contactsCount: 45,
    additionalAttributes: {
      industry: 'Defense',
      phone: '+1 (555) 555-0199',
      email: 'info@stark.com',
      website: 'www.stark.com',
      owner: 'Tony Stark',
    },
  },
  {
    id: 90004,
    name: 'Wayne Enterprises',
    domain: 'microsoft.com',
    contactsCount: 24,
    additionalAttributes: {
      industry: 'Conglomerate',
      phone: '+1 (555) 012-3456',
      email: 'business@wayne.com',
      website: 'www.wayne.com',
      owner: 'Bruce Wayne',
    },
  },
  {
    id: 90005,
    name: 'Pied Piper',
    domain: 'dropbox.com',
    contactsCount: 5,
    additionalAttributes: {
      industry: 'Data Storage',
      phone: '+1 (555) 888-9999',
      email: 'richard@piedpiper.com',
      website: 'www.piedpiper.com',
      owner: 'Richard H.',
    },
  },
  {
    id: 90006,
    name: 'Hooli',
    domain: 'google.com',
    contactsCount: 112,
    additionalAttributes: {
      industry: 'Technology',
      phone: '+1 (555) 777-8888',
      email: 'info@hooli.com',
      website: 'www.hooli.com',
      owner: 'Gavin Belson',
    },
  },
];
