import { createRouter, createWebHistory, type RouteRecordRaw } from 'vue-router'
import DefaultLayout from '@/layouts/DefaultLayout.vue'
import BareLayout from '@/layouts/BareLayout.vue'

const shellRoutes: RouteRecordRaw[] = [
  { path: "/inbox", name: "r_inbox", component: () => import('@/views/inbox/InboxView.vue'), meta: { title: "My Inbox" } },
  { path: "/conversations", name: "r_conversations", component: () => import('@/views/conversations/ConversationsView.vue'), meta: { title: "Conversations" } },
  { path: "/contacts", name: "r_contacts", component: () => import('@/views/contacts/ContactsView.vue'), meta: { title: "Contacts" } },
  { path: "/companies", name: "r_companies", component: () => import('@/views/companies/CompaniesView.vue'), meta: { title: "Companies" } },
  { path: "/deals", name: "r_deals", component: () => import('@/views/deals/DealsView.vue'), meta: { title: "Deals" } },
  { path: "/pipelines", name: "r_pipelines", component: () => import('@/views/pipelines/PipelinesView.vue'), meta: { title: "Pipelines" } },
  { path: "/opportunities", name: "r_opportunities", component: () => import('@/views/opportunities/OpportunitiesView.vue'), meta: { title: "Opportunities" } },
  { path: "/", name: "r_dashboard", component: () => import('@/views/dashboard/DashboardView.vue'), meta: { title: "Dashboard" } },
  { path: "/tasks", name: "r_tasks", component: () => import('@/views/tasks/TasksView.vue'), meta: { title: "Tasks" } },
  { path: "/calendar", name: "r_calendar", component: () => import('@/views/calendar/CalendarView.vue'), meta: { title: "Calendar" } },
  { path: "/campaigns", name: "r_campaigns", component: () => import('@/views/campaigns/CampaignsView.vue'), meta: { title: "Campaigns" } },
  { path: "/campaigns/live-chat", name: "r_campaigns_live_chat", component: () => import('@/views/campaigns/LiveChatCampaignsView.vue'), meta: { title: "Campaigns" } },
  { path: "/campaigns/sms", name: "r_campaigns_sms", component: () => import('@/views/campaigns/SMSCampaignsView.vue'), meta: { title: "Campaigns" } },
  { path: "/campaigns/whatsapp", name: "r_campaigns_whatsapp", component: () => import('@/views/campaigns/WhatsAppCampaignsView.vue'), meta: { title: "Campaigns" } },
  { path: "/funnels", name: "r_funnels", component: () => import('@/views/funnels/FunnelsView.vue'), meta: { title: "Funnels" } },
  { path: "/landing-pages", name: "r_landing_pages", component: () => import('@/views/landing-pages/LandingPagesView.vue'), meta: { title: "Landing Pages" } },
  { path: "/forms", name: "r_forms", component: () => import('@/views/forms/FormsView.vue'), meta: { title: "Forms" } },
  { path: "/surveys", name: "r_surveys", component: () => import('@/views/surveys/SurveysView.vue'), meta: { title: "Surveys" } },
  
  // AI & Automation
  { path: "/ai/faqs", name: "r_ai_faqs", component: () => import('@/views/ai/FAQsView.vue'), meta: { title: "FAQs" } },
  { path: "/ai/documents", name: "r_ai_documents", component: () => import('@/views/ai/DocumentsView.vue'), meta: { title: "Documents" } },
  { path: "/ai/scenarios", name: "r_ai_scenarios", component: () => import('@/views/ai/ScenariosView.vue'), meta: { title: "Scenarios" } },
  { path: "/ai/playground", name: "r_ai_playground", component: () => import('@/views/ai/PlaygroundView.vue'), meta: { title: "Playground" } },
  { path: "/ai/inboxes", name: "r_ai_inboxes", component: () => import('@/views/ai/InboxesView.vue'), meta: { title: "Inboxes" } },
  { path: "/ai/tools", name: "r_ai_tools", component: () => import('@/views/ai/ToolsView.vue'), meta: { title: "Tools" } },
  { path: "/ai/settings", name: "r_ai_settings", component: () => import('@/views/ai/SettingsView.vue'), meta: { title: "Settings" } },
  { path: "/captain", name: "r_captain", component: () => import('@/views/captain/CaptainAiView.vue'), meta: { title: "Relay AI" } },
  { path: "/copilot", name: "r_copilot", component: () => import('@/views/copilot/CopilotView.vue'), meta: { title: "AI Copilot" } },
  { path: "/prompt-library", name: "r_prompt_library", component: () => import('@/views/prompt-library/PromptLibraryView.vue'), meta: { title: "Prompt Library" } },
  { path: "/knowledge-base", name: "r_knowledge_base", component: () => import('@/views/knowledge-base/KnowledgeBaseView.vue'), meta: { title: "Knowledge Base" } },
  { path: "/workflows", name: "r_workflows", component: () => import('@/views/workflows/WorkflowsView.vue'), meta: { title: "Workflows" } },
  { path: "/templates", name: "r_templates", component: () => import('@/views/templates/TemplatesView.vue'), meta: { title: "Templates" } },
  { path: "/triggers", name: "r_triggers", component: () => import('@/views/triggers/TriggersView.vue'), meta: { title: "Triggers" } },
  
  // Reputation
  { path: "/reputation/overview", name: "r_reputation_overview", component: () => import('@/views/reputation/OverviewView.vue'), meta: { title: "Reputation Overview" } },
  { path: "/reviews", name: "r_reviews", component: () => import('@/views/reviews/ReviewsView.vue'), meta: { title: "Reviews" } },
  { path: "/reputation/outreach", name: "r_reputation_outreach", component: () => import('@/views/reputation/ReviewOutreachView.vue'), meta: { title: "Configuration" } },
  { path: "/reputation/integrations", name: "r_reputation_integrations", component: () => import('@/views/reputation/IntegrationsView.vue'), meta: { title: "Reputation Integrations" } },
  { path: "/video-reviews", name: "r_video_reviews", component: () => import('@/views/reputation/VideoReviewsView.vue'), meta: { title: "Video Testimonials" } },
  { path: "/listings", name: "r_listings", component: () => import('@/views/listings/ListingsView.vue'), meta: { title: "Listings" } },
  { path: "/listings/:id", name: "r_listing_detail", component: () => import('@/views/listings/ListingDetailView.vue'), meta: { title: "Listing Details" } },
  { path: "/reputation/settings", name: "r_reputation_settings", component: () => import('@/views/reputation/SettingsView.vue'), meta: { title: "Reputation Settings" } },
  { path: "/feedback", name: "r_feedback", component: () => import('@/views/feedback/FeedbackView.vue'), meta: { title: "Feedback" } },
  
  // Analytics
  { path: "/reports", name: "r_reports", component: () => import('@/views/reports/ReportsView.vue'), meta: { title: "Reports" } },
  { path: "/analytics/dashboards", name: "r_analytics_dashboards", component: () => import('@/views/analytics/DashboardsView.vue'), meta: { title: "Dashboards" } },
  { path: "/analytics/revenue", name: "r_analytics_revenue", component: () => import('@/views/analytics/RevenueAnalyticsView.vue'), meta: { title: "Revenue Analytics" } },
  { path: "/analytics/campaigns", name: "r_analytics_campaigns", component: () => import('@/views/analytics/CampaignAnalyticsView.vue'), meta: { title: "Campaign Analytics" } },
  
  // Administration
  { path: "/admin/team", name: "r_admin_team", component: () => import('@/views/admin/TeamView.vue'), meta: { title: "Team" } },
  { path: "/admin/roles", name: "r_admin_roles", component: () => import('@/views/admin/RolesView.vue'), meta: { title: "Roles & Permissions" } },
  { path: "/admin/billing", name: "r_admin_billing", component: () => import('@/views/admin/BillingView.vue'), meta: { title: "Billing & Usage" } },
  { path: "/admin/integrations", name: "r_admin_integrations", component: () => import('@/views/admin/IntegrationsView.vue'), meta: { title: "Integrations" } },
  { path: "/admin/api", name: "r_admin_api", component: () => import('@/views/admin/ApiView.vue'), meta: { title: "API Keys" } },
  { path: "/admin/settings", name: "r_admin_settings", component: () => import('@/views/admin/SettingsView.vue'), meta: { title: "Admin Settings" } },
  { path: "/settings", name: "r_settings", component: () => import('@/views/settings/SettingsView.vue'), meta: { title: "Settings" } },
  { path: "/profile-settings", name: "r_profile_settings", component: () => import('@/views/settings/ProfileSettingsView.vue'), meta: { title: "Profile Settings" } },
  { path: "/profile/mfa", name: "r_profile_mfa", component: () => import('@/views/settings/ProfileMfaView.vue'), meta: { title: "Two-Factor Authentication" } },
  { path: "/support", redirect: "/support/articles" },
  { path: "/support/:tab", name: "r_support", component: () => import('@/views/support/SupportView.vue'), meta: { title: "Knowledge Base" } },

  // User States
  { path: "/user-states/empty-state", name: "r_user_state_empty", component: () => import('@/views/user-states/EmptyStateView.vue'), meta: { title: "Empty State" } },
  { path: "/user-states/loading-state", name: "r_user_state_loading", component: () => import('@/views/user-states/LoadingStateView.vue'), meta: { title: "Loading State" } },
  { path: "/user-states/error-state", name: "r_user_state_error", component: () => import('@/views/user-states/ErrorStateView.vue'), meta: { title: "Error State" } },
  { path: "/user-states/no-internet", name: "r_user_state_no_internet", component: () => import('@/views/user-states/NoInternetView.vue'), meta: { title: "No Internet" } },
  { path: "/user-states/slow-network", name: "r_user_state_slow_network", component: () => import('@/views/user-states/SlowNetworkView.vue'), meta: { title: "Slow Network" } },
  { path: "/user-states/no-search-results", name: "r_user_state_no_search_results", component: () => import('@/views/user-states/NoSearchResultsView.vue'), meta: { title: "No Search Results" } },
  { path: "/user-states/permission-denied", name: "r_user_state_permission_denied", component: () => import('@/views/user-states/PermissionDeniedView.vue'), meta: { title: "Permission Denied" } },
  { path: "/user-states/session-expired", name: "r_user_state_session_expired", component: () => import('@/views/user-states/SessionExpiredView.vue'), meta: { title: "Session Expired" } },
  { path: "/user-states/form-validation", name: "r_user_state_form_validation", component: () => import('@/views/user-states/FormValidationView.vue'), meta: { title: "Form Validation" } },
  { path: "/user-states/success-state", name: "r_user_state_success", component: () => import('@/views/user-states/SuccessStateView.vue'), meta: { title: "Success State" } },

  // Detail routes that exist in the reference (dynamic slugs/ids). Reuse the matching
  // existing detail views where one exists; dedicated views for the rest.
  { path: "/todo/task/:id", name: "r_todo_task", component: () => import('@/views/todo/TodoTask.vue'), meta: { title: "Task" } },
  { path: "/original/tasks/:id", name: "r_original_task", component: () => import('@/views/original/OriginalTask.vue'), meta: { title: "Task Details" } },
  // Reference opens these as intercepting-route drawers (uncapturable headlessly); built as
  // on-brand detail pages from the list data.
  { path: "/original/users/:id", name: "r_original_user", component: () => import('@/views/original/OriginalUser.vue'), meta: { title: "Profile" } },
  { path: "/developers/webhooks/:id", name: "r_developers_webhook", component: () => import('@/views/developers/DevelopersWebhook.vue'), meta: { title: "Webhook Details" } },
  { path: "/ecommerce/product-detail/:slug", name: "r_ecommerce_product_detail_slug", component: () => import('@/views/ecommerce/EcommerceProductDetail1.vue'), meta: { title: "Product Detail" } },
  { path: "/ecommerce/edit-product/:slug", name: "r_ecommerce_edit_product_slug", component: () => import('@/views/ecommerce/EcommerceEditProductRadianceRitualSet.vue'), meta: { title: "Edit Product" } },
  { path: "/developers/api-keys", name: "r_developers_api_keys", component: () => import('@/views/developers/DevelopersApiKeys.vue'), meta: { title: "Api Keys" } },
  { path: "/developers/events-&-logs", name: "r_developers_events_logs", component: () => import('@/views/developers/DevelopersEventsLogs.vue'), meta: { title: "Events & Logs" } },
  { path: "/developers/overview", name: "r_developers_overview", component: () => import('@/views/developers/DevelopersOverview.vue'), meta: { title: "Overview" } },
  { path: "/developers/webhooks", name: "r_developers_webhooks", component: () => import('@/views/developers/DevelopersWebhooks.vue'), meta: { title: "Webhooks" } },
  { path: "/ecommerce/add-customer", name: "r_ecommerce_add_customer", component: () => import('@/views/ecommerce/EcommerceAddCustomer.vue'), meta: { title: "Add Customer" } },
  { path: "/ecommerce/add-order", name: "r_ecommerce_add_order", component: () => import('@/views/ecommerce/EcommerceAddOrder.vue'), meta: { title: "Add Order" } },
  { path: "/ecommerce/add-product", name: "r_ecommerce_add_product", component: () => import('@/views/ecommerce/EcommerceAddProduct.vue'), meta: { title: "Add Product" } },
  { path: "/ecommerce/add-product-2", name: "r_ecommerce_add_product_2", component: () => import('@/views/ecommerce/EcommerceAddProduct2.vue'), meta: { title: "Add Product 2" } },
  { path: "/ecommerce/add-shipping", name: "r_ecommerce_add_shipping", component: () => import('@/views/ecommerce/EcommerceAddShipping.vue'), meta: { title: "Add Shipping" } },
  { path: "/ecommerce/customer-detail-1", name: "r_ecommerce_customer_detail_1", component: () => import('@/views/ecommerce/EcommerceCustomerDetail1.vue'), meta: { title: "Customer Detail 1" } },
  { path: "/ecommerce/customer-list-1", name: "r_ecommerce_customer_list_1", component: () => import('@/views/ecommerce/EcommerceCustomerList1.vue'), meta: { title: "Customer List 1" } },
  { path: "/ecommerce/dashboard-1", name: "r_ecommerce_dashboard_1", component: () => import('@/views/ecommerce/EcommerceDashboard1.vue'), meta: { title: "Dashboard 1" } },
  { path: "/ecommerce/dashboard-2", name: "r_ecommerce_dashboard_2", component: () => import('@/views/ecommerce/EcommerceDashboard2.vue'), meta: { title: "Dashboard 2" } },
  { path: "/ecommerce/dashboard-3", name: "r_ecommerce_dashboard_3", component: () => import('@/views/ecommerce/EcommerceDashboard3.vue'), meta: { title: "Dashboard 3" } },
  { path: "/ecommerce/dashboard-4", name: "r_ecommerce_dashboard_4", component: () => import('@/views/ecommerce/EcommerceDashboard4.vue'), meta: { title: "Dashboard 4" } },
  { path: "/ecommerce/dashboard-5", name: "r_ecommerce_dashboard_5", component: () => import('@/views/ecommerce/EcommerceDashboard5.vue'), meta: { title: "Dashboard 5" } },
  { path: "/ecommerce/dashboard-6", name: "r_ecommerce_dashboard_6", component: () => import('@/views/ecommerce/EcommerceDashboard6.vue'), meta: { title: "Dashboard 6" } },
  { path: "/ecommerce/dashboard-7", name: "r_ecommerce_dashboard_7", component: () => import('@/views/ecommerce/EcommerceDashboard7.vue'), meta: { title: "Dashboard 7" } },
  { path: "/ecommerce/dashboard-8", name: "r_ecommerce_dashboard_8", component: () => import('@/views/ecommerce/EcommerceDashboard8.vue'), meta: { title: "Dashboard 8" } },
  { path: "/ecommerce/dashboard-9", name: "r_ecommerce_dashboard_9", component: () => import('@/views/ecommerce/EcommerceDashboard9.vue'), meta: { title: "Dashboard 9" } },
  { path: "/ecommerce/edit-customer/cus-1742", name: "r_ecommerce_edit_customer_cus_1742", component: () => import('@/views/ecommerce/EcommerceEditCustomerCus1742.vue'), meta: { title: "Cus 1742" } },
  { path: "/ecommerce/edit-order/so-654", name: "r_ecommerce_edit_order_so_654", component: () => import('@/views/ecommerce/EcommerceEditOrderSo654.vue'), meta: { title: "So 654" } },
  { path: "/ecommerce/edit-product-2/radiance-ritual-set", name: "r_ecommerce_edit_product_2_radiance_ritual_set", component: () => import('@/views/ecommerce/EcommerceEditProduct2RadianceRitualSet.vue'), meta: { title: "Radiance Ritual Set" } },
  { path: "/ecommerce/edit-product/radiance-ritual-set", name: "r_ecommerce_edit_product_radiance_ritual_set", component: () => import('@/views/ecommerce/EcommerceEditProductRadianceRitualSet.vue'), meta: { title: "Radiance Ritual Set" } },
  { path: "/ecommerce/edit-shipping", name: "r_ecommerce_edit_shipping", component: () => import('@/views/ecommerce/EcommerceEditShipping.vue'), meta: { title: "Edit Shipping" } },
  { path: "/ecommerce/order-detail-1", name: "r_ecommerce_order_detail_1", component: () => import('@/views/ecommerce/EcommerceOrderDetail1.vue'), meta: { title: "Order Detail 1" } },
  { path: "/ecommerce/order-detail-2", name: "r_ecommerce_order_detail_2", component: () => import('@/views/ecommerce/EcommerceOrderDetail2.vue'), meta: { title: "Order Detail 2" } },
  { path: "/ecommerce/order-list-1", name: "r_ecommerce_order_list_1", component: () => import('@/views/ecommerce/EcommerceOrderList1.vue'), meta: { title: "Order List 1" } },
  { path: "/ecommerce/order-list-2", name: "r_ecommerce_order_list_2", component: () => import('@/views/ecommerce/EcommerceOrderList2.vue'), meta: { title: "Order List 2" } },
  { path: "/ecommerce/order-list-3", name: "r_ecommerce_order_list_3", component: () => import('@/views/ecommerce/EcommerceOrderList3.vue'), meta: { title: "Order List 3" } },
  { path: "/ecommerce/product-detail-1", name: "r_ecommerce_product_detail_1", component: () => import('@/views/ecommerce/EcommerceProductDetail1.vue'), meta: { title: "Product Detail 1" } },
  { path: "/ecommerce/product-detail-2", name: "r_ecommerce_product_detail_2", component: () => import('@/views/ecommerce/EcommerceProductDetail2.vue'), meta: { title: "Product Detail 2" } },
  { path: "/ecommerce/product-list-1", name: "r_ecommerce_product_list_1", component: () => import('@/views/ecommerce/EcommerceProductList1.vue'), meta: { title: "Product List 1" } },
  { path: "/ecommerce/product-list-2", name: "r_ecommerce_product_list_2", component: () => import('@/views/ecommerce/EcommerceProductList2.vue'), meta: { title: "Product List 2" } },
  { path: "/ecommerce/product-list-3", name: "r_ecommerce_product_list_3", component: () => import('@/views/ecommerce/EcommerceProductList3.vue'), meta: { title: "Product List 3" } },
  { path: "/ecommerce/product-list-4", name: "r_ecommerce_product_list_4", component: () => import('@/views/ecommerce/EcommerceProductList4.vue'), meta: { title: "Product List 4" } },
  { path: "/ecommerce/shipment-detail-1", name: "r_ecommerce_shipment_detail_1", component: () => import('@/views/ecommerce/EcommerceShipmentDetail1.vue'), meta: { title: "Shipment Detail 1" } },
  { path: "/ecommerce/shipment-list-1", name: "r_ecommerce_shipment_list_1", component: () => import('@/views/ecommerce/EcommerceShipmentList1.vue'), meta: { title: "Shipment List 1" } },
  { path: "/original/dashboard-10", name: "r_original_dashboard_10", component: () => import('@/views/original/OriginalDashboard10.vue'), meta: { title: "Dashboard 10" } },
  { path: "/original/dashboard-11", name: "r_original_dashboard_11", component: () => import('@/views/original/OriginalDashboard11.vue'), meta: { title: "Dashboard 11" } },
  { path: "/original/dashboard-12", name: "r_original_dashboard_12", component: () => import('@/views/original/OriginalDashboard12.vue'), meta: { title: "Dashboard 12" } },
  { path: "/original/settings", name: "r_original_settings", component: () => import('@/views/original/OriginalSettings.vue'), meta: { title: "Settings" } },
  { path: "/original/settings/billing", name: "r_original_settings_billing", component: () => import('@/views/original/OriginalSettingsBilling.vue'), meta: { title: "Billing" } },
  { path: "/original/settings/connected-apps", name: "r_original_settings_connected_apps", component: () => import('@/views/original/OriginalSettingsConnectedApps.vue'), meta: { title: "Connected Apps" } },
  { path: "/original/settings/notifications", name: "r_original_settings_notifications", component: () => import('@/views/original/OriginalSettingsNotifications.vue'), meta: { title: "Notifications" } },
  { path: "/original/settings/plans", name: "r_original_settings_plans", component: () => import('@/views/original/OriginalSettingsPlans.vue'), meta: { title: "Plans" } },
  { path: "/original/settings/profile", name: "r_original_settings_profile", component: () => import('@/views/original/OriginalSettingsProfile.vue'), meta: { title: "Profile" } },
  { path: "/original/tasks", name: "r_original_tasks", component: () => import('@/views/original/OriginalTasks.vue'), meta: { title: "Tasks" } },
  { path: "/original/users", name: "r_original_users", component: () => import('@/views/original/OriginalUsers.vue'), meta: { title: "Users" } },
  { path: "/project-management/dashboard-1", name: "r_project_management_dashboard_1", component: () => import('@/views/project-management/ProjectManagementDashboard1.vue'), meta: { title: "Dashboard 1" } },
  { path: "/project-management/dashboard-2", name: "r_project_management_dashboard_2", component: () => import('@/views/project-management/ProjectManagementDashboard2.vue'), meta: { title: "Dashboard 2" } },
  { path: "/project-management/dashboard-3", name: "r_project_management_dashboard_3", component: () => import('@/views/project-management/ProjectManagementDashboard3.vue'), meta: { title: "Dashboard 3" } },
  { path: "/project-management/dashboard-4", name: "r_project_management_dashboard_4", component: () => import('@/views/project-management/ProjectManagementDashboard4.vue'), meta: { title: "Dashboard 4" } },
  { path: "/project-management/inbox-1", name: "r_project_management_inbox_1", component: () => import('@/views/project-management/ProjectManagementInbox1.vue'), meta: { title: "Inbox 1" } },
  { path: "/project-management/inbox-2", name: "r_project_management_inbox_2", component: () => import('@/views/project-management/ProjectManagementInbox2.vue'), meta: { title: "Inbox 2" } },
  { path: "/project-management/inbox-3", name: "r_project_management_inbox_3", component: () => import('@/views/project-management/ProjectManagementInbox3.vue'), meta: { title: "Inbox 3" } },
  { path: "/project-management/inbox-4", name: "r_project_management_inbox_4", component: () => import('@/views/project-management/ProjectManagementInbox4.vue'), meta: { title: "Inbox 4" } },
  { path: "/project-management/inbox-email-1", name: "r_project_management_inbox_email_1", component: () => import('@/views/project-management/ProjectManagementInboxEmail1.vue'), meta: { title: "Inbox Email 1" } },
  { path: "/project-management/issue-calendar-1", name: "r_project_management_issue_calendar_1", component: () => import('@/views/project-management/ProjectManagementIssueCalendar1.vue'), meta: { title: "Issue Calendar 1" } },
  { path: "/project-management/issue-calendar-2", name: "r_project_management_issue_calendar_2", component: () => import('@/views/project-management/ProjectManagementIssueCalendar2.vue'), meta: { title: "Issue Calendar 2" } },
  { path: "/project-management/issue-detail-1", name: "r_project_management_issue_detail_1", component: () => import('@/views/project-management/ProjectManagementIssueDetail1.vue'), meta: { title: "Issue Detail 1" } },
  { path: "/project-management/issue-detail-2", name: "r_project_management_issue_detail_2", component: () => import('@/views/project-management/ProjectManagementIssueDetail2.vue'), meta: { title: "Issue Detail 2" } },
  { path: "/project-management/issue-gantt-1", name: "r_project_management_issue_gantt_1", component: () => import('@/views/project-management/ProjectManagementIssueGantt1.vue'), meta: { title: "Issue Gantt 1" } },
  { path: "/project-management/issue-kanban-1", name: "r_project_management_issue_kanban_1", component: () => import('@/views/project-management/ProjectManagementIssueKanban1.vue'), meta: { title: "Issue Kanban 1" } },
  { path: "/project-management/issue-kanban-2", name: "r_project_management_issue_kanban_2", component: () => import('@/views/project-management/ProjectManagementIssueKanban2.vue'), meta: { title: "Issue Kanban 2" } },
  { path: "/project-management/issue-kanban-3", name: "r_project_management_issue_kanban_3", component: () => import('@/views/project-management/ProjectManagementIssueKanban3.vue'), meta: { title: "Issue Kanban 3" } },
  { path: "/project-management/issue-list-1", name: "r_project_management_issue_list_1", component: () => import('@/views/project-management/ProjectManagementIssueList1.vue'), meta: { title: "Issue List 1" } },
  { path: "/project-management/issue-list-2", name: "r_project_management_issue_list_2", component: () => import('@/views/project-management/ProjectManagementIssueList2.vue'), meta: { title: "Issue List 2" } },
  { path: "/project-management/issue-spreadsheet-1", name: "r_project_management_issue_spreadsheet_1", component: () => import('@/views/project-management/ProjectManagementIssueSpreadsheet1.vue'), meta: { title: "Issue Spreadsheet 1" } },
  { path: "/project-management/member-list-1", name: "r_project_management_member_list_1", component: () => import('@/views/project-management/ProjectManagementMemberList1.vue'), meta: { title: "Member List 1" } },
  { path: "/project-management/member-list-2", name: "r_project_management_member_list_2", component: () => import('@/views/project-management/ProjectManagementMemberList2.vue'), meta: { title: "Member List 2" } },
  { path: "/project-management/member-list-3", name: "r_project_management_member_list_3", component: () => import('@/views/project-management/ProjectManagementMemberList3.vue'), meta: { title: "Member List 3" } },
  { path: "/project-management/project-detail-1", name: "r_project_management_project_detail_1", component: () => import('@/views/project-management/ProjectManagementProjectDetail1.vue'), meta: { title: "Project Detail 1" } },
  { path: "/project-management/project-detail-2", name: "r_project_management_project_detail_2", component: () => import('@/views/project-management/ProjectManagementProjectDetail2.vue'), meta: { title: "Project Detail 2" } },
  { path: "/project-management/project-list-1", name: "r_project_management_project_list_1", component: () => import('@/views/project-management/ProjectManagementProjectList1.vue'), meta: { title: "Project List 1" } },
  { path: "/project-management/project-list-2", name: "r_project_management_project_list_2", component: () => import('@/views/project-management/ProjectManagementProjectList2.vue'), meta: { title: "Project List 2" } },
  { path: "/project-management/project-list-3", name: "r_project_management_project_list_3", component: () => import('@/views/project-management/ProjectManagementProjectList3.vue'), meta: { title: "Project List 3" } },
  { path: "/project-management/project-list-4", name: "r_project_management_project_list_4", component: () => import('@/views/project-management/ProjectManagementProjectList4.vue'), meta: { title: "Project List 4" } },
  { path: "/project-management/team-list-1", name: "r_project_management_team_list_1", component: () => import('@/views/project-management/ProjectManagementTeamList1.vue'), meta: { title: "Team List 1" } },
  { path: "/project-management/team-list-2", name: "r_project_management_team_list_2", component: () => import('@/views/project-management/ProjectManagementTeamList2.vue'), meta: { title: "Team List 2" } },
  { path: "/project-management/team-list-3", name: "r_project_management_team_list_3", component: () => import('@/views/project-management/ProjectManagementTeamList3.vue'), meta: { title: "Team List 3" } },
  { path: "/todo", name: "r_todo", component: () => import('@/views/todo/Todo.vue'), meta: { title: "Todo" } },
  { path: "/todo/activity", name: "r_todo_activity", component: () => import('@/views/todo/TodoActivity.vue'), meta: { title: "Activity" } },
  { path: "/todo/deleted", name: "r_todo_deleted", component: () => import('@/views/todo/TodoDeleted.vue'), meta: { title: "Deleted" } },
  { path: "/todo/important", name: "r_todo_important", component: () => import('@/views/todo/TodoImportant.vue'), meta: { title: "Important" } },
  { path: "/todo/notifications", name: "r_todo_notifications", component: () => import('@/views/todo/TodoNotifications.vue'), meta: { title: "Notifications" } },
  { path: "/todo/projects/fitness", name: "r_todo_projects_fitness", component: () => import('@/views/todo/TodoProjectsFitness.vue'), meta: { title: "Fitness" } },
  { path: "/todo/projects/learning", name: "r_todo_projects_learning", component: () => import('@/views/todo/TodoProjectsLearning.vue'), meta: { title: "Learning" } },
  { path: "/todo/projects/personal", name: "r_todo_projects_personal", component: () => import('@/views/todo/TodoProjectsPersonal.vue'), meta: { title: "Personal" } },
  { path: "/todo/projects/shopping", name: "r_todo_projects_shopping", component: () => import('@/views/todo/TodoProjectsShopping.vue'), meta: { title: "Shopping" } },
  { path: "/todo/projects/work", name: "r_todo_projects_work", component: () => import('@/views/todo/TodoProjectsWork.vue'), meta: { title: "Work" } },
  { path: "/todo/settings", name: "r_todo_settings", component: () => import('@/views/todo/TodoSettings.vue'), meta: { title: "Settings" } },
  { path: "/todo/tasks/new", name: "r_todo_tasks_new", component: () => import('@/views/todo/TodoTasksNew.vue'), meta: { title: "New" } },
  { path: "/todo/today", name: "r_todo_today", component: () => import('@/views/todo/TodoToday.vue'), meta: { title: "Today" } },
  { path: "/todo/upcoming", name: "r_todo_upcoming", component: () => import('@/views/todo/TodoUpcoming.vue'), meta: { title: "Upcoming" } }
]

const bareRoutes: RouteRecordRaw[] = [

  { path: "/401", name: "r_401", component: () => import('@/views/errors/P401.vue'), meta: { title: "401" } },
  { path: "/403", name: "r_403", component: () => import('@/views/errors/P403.vue'), meta: { title: "403" } },
  { path: "/404", name: "r_404", component: () => import('@/views/errors/P404.vue'), meta: { title: "404" } },
  { path: "/503", name: "r_503", component: () => import('@/views/errors/P503.vue'), meta: { title: "503" } },
  { path: "/error", name: "r_error", component: () => import('@/views/errors/Error.vue'), meta: { title: "Error" } },
  { path: "/forgot-password", name: "r_forgot_password", component: () => import('@/views/auth/ForgotPassword.vue'), meta: { title: "Forgot Password" } },
  { path: "/sso", name: "r_sso_login", component: () => import('@/views/auth/SsoLogin.vue'), meta: { title: "SSO Login" } },
  { path: "/login", name: "r_login", component: () => import('@/views/auth/Login.vue'), meta: { title: "Login" } },
  { path: "/register", name: "r_register", component: () => import('@/views/auth/Register.vue'), meta: { title: "Register" } },
  { path: "/onboarding", name: "r_onboarding", component: () => import('@/views/auth/OnboardingView.vue'), meta: { title: "Onboarding" } },
  { path: "/onboarding-2", name: "r_onboarding_2", component: () => import('@/views/auth/Onboarding2View.vue'), meta: { title: "Onboarding 2" } }
]

const routes: RouteRecordRaw[] = [
  { path: '/', redirect: '/ecommerce/dashboard-1' },
  { path: '/', component: DefaultLayout, children: shellRoutes },
  { path: '/', component: BareLayout, children: bareRoutes },
  { path: '/:pathMatch(.*)*', redirect: '/404' },
]
export const router = createRouter({ history: createWebHistory(), routes, scrollBehavior: () => ({ top: 0 }) })
