export default [
  {
    id: 90001,
    name: 'Enterprise License',
    amountCents: 15000000,
    currency: 'USD',
    closeOn: '2026-10-12',
    priority: 'high',
    probability: 70,
    updatedAt: '2026-09-06T10:00:00Z',
    company: { name: 'Acme Inc.' },
    owner: { name: 'Jane Doe', availableName: 'Jane Doe' },
    pipelineStage: { name: 'Proposal', isWon: false, isLost: false },
  },
  {
    id: 90002,
    name: 'Platform Renewal',
    amountCents: 8200000,
    currency: 'USD',
    closeOn: '2026-09-22',
    priority: 'medium',
    probability: 45,
    updatedAt: '2026-09-05T14:00:00Z',
    company: { name: 'Global Tech' },
    owner: { name: 'John Smith', availableName: 'John Smith' },
    pipelineStage: { name: 'Negotiation', isWon: false, isLost: false },
  },
  {
    id: 90003,
    name: 'Cloud Migration',
    amountCents: 5600000,
    currency: 'USD',
    closeOn: '2026-11-03',
    priority: 'low',
    probability: 25,
    updatedAt: '2026-09-04T09:00:00Z',
    company: { name: 'Wayne Enterprises' },
    owner: { name: 'Alex Turner', availableName: 'Alex Turner' },
    pipelineStage: { name: 'Lead', isWon: false, isLost: false },
  },
];
